# -*- coding: utf-8 -*-
"""Tensorflow-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IakyX1qzIO8e8mF5Zr4NzpetQWou3-5l
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras

model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape = [1])])

model.compile(optimizer="sgd", loss="mean_squared_error")

xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

model.fit(xs,ys,epochs=500)

print(model.predict([10.0]))

